import Head from 'next/head'
import {Button} from 'antd';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div className={"text-blue"}>Welcome to Next.js!</div>
          <Button type="primary">Button</Button>
      </main>

      <footer className={styles.footer}>
        测试
      </footer>
    </div>
  )
}
